version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/sso"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/iam"
    schedule:
      interval: "weekly"
