name: Build and Test

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Gradle Build
        run: |
          ./gradlew clean build -Dsonar.host.url=$SONAR_HOST -Dsonar.login=$SONAR_LOGIN
        env:
          SONAR_HOST: ${{ secrets.SONAR_HOST }}
          SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
