name: Build and Test

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Calculate version
        id: spell
        uses: actoaps/version-spell@v3

      - name: Setup java 18
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '18'

      - name: Gradle Build
        run: |
          ./gradlew clean build -Dsonar.host.url=$SONAR_HOST -Dsonar.login=$SONAR_LOGIN -DversionOverride=$BUILD_ID
        env:
          SONAR_HOST: ${{ secrets.SONAR_HOST }}
          SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
          BUILD_ID: ${{ steps.spell.outputs.version }}
