name: Release to Docker

on:
  push:
    branches:
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Calculate version
        id: spell
        uses: actoaps/version-spell@v3

      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Gradle Build
        run: |
          ./gradlew clean build -Dsonar.host.url=$SONAR_HOST -Dsonar.login=$SONAR_LOGIN -DversionOverride=$BUILD_ID
        env:
          SONAR_HOST: ${{ secrets.SONAR_HOST }}
          SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
          BUILD_ID: ${{ steps.spell.outputs.version }}

      - name: Import GPG key
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v2
        env:
          GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}

      - name: Release client to Maven Central
        run: |
          gpg --export-secret-keys > secring.gpg
          ./gradlew :client:uploadArchives -Psigning.keyId=$KEY_ID -Psigning.password="" -Psigning.secretKeyRingFile=../secring.gpg -PnexusUsername=$USERNAME -PnexusPassword=$PASSWORD -DversionOverride=$BUILD_ID
          ./gradlew closeAndReleaseRepository -PnexusUsername=$USERNAME -PnexusPassword=$PASSWORD
        env:
          KEY_ID: ${{ secrets.MAVEN_GPG_KEY_ID }}
          USERNAME: ${{ secrets.OSSRH_USERNAME }}
          PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          BUILD_ID: ${{ steps.spell.outputs.version }}

      - name: Release to Docker
        run: |
          docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
          docker build -t actoaps/fafnir-sso:$BUILD_ID ./auth
          docker tag actoaps/fafnir-sso:$BUILD_ID actoaps/fafnir-sso:latest
          docker push actoaps/fafnir-sso:$BUILD_ID
          docker push actoaps/fafnir-sso:latest
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          BUILD_ID: ${{ steps.spell.outputs.version }}
